import '@/plugins/cookies'
import '@/plugins/log'
import '@/plugins/axios'
import '@/plugins/http'
import '@/plugins/weui'
import '@/plugins/jssdk'
import '@/plugins/cos'
import '@/plugins/ui'
// import '@/plugins/aegis'
